//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtractorUtils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExtractorUtils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xml&gt;
        ///  &lt;cardsUrl value=&quot;http://www.thronesdb.com/api/public/cards/&quot; /&gt;
        ///  &lt;packsUrl value=&quot;http://www.thronesdb.com/api/public/packs/&quot; /&gt;
        ///  &lt;dbImageUrl value=&quot;http://www.thronesdb.com/bundles/cards/&quot; /&gt;
        ///  &lt;cgImageUrl value=&quot;http://lcg-cdn.fantasyflightgames.com/got2nd/&quot; /&gt;
        ///  &lt;properties&gt;
        ///    &lt;property octgn_name=&quot;Type&quot; db_name=&quot;type_name&quot; /&gt;
        ///    &lt;property octgn_name=&quot;Faction&quot; db_name=&quot;faction_name&quot; /&gt;
        ///    &lt;property octgn_name=&quot;Text&quot; db_name=&quot;text&quot; type=&quot;Rich&quot;/&gt;
        ///    &lt;property octgn_name=&quot;Traits&quot; db_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xml&gt;
        ///  &lt;sets&gt;
        ///    &lt;cycle value=&quot;0&quot;&gt;
        ///      &lt;set name=&quot;1&quot; cgdb_id=&quot;00&quot; value=&quot;acefd680-bd02-4d95-8c23-f5c6207ee0df&quot; /&gt;
        ///    &lt;/cycle&gt;
        ///    &lt;cycle value=&quot;1&quot;&gt;
        ///      &lt;set name=&quot;1&quot; cgdb_id=&quot;01&quot; value=&quot;c64ccfe4-8aea-4c65-9611-3e46739813d9&quot; /&gt;
        ///    &lt;/cycle&gt;
        ///    &lt;cycle value=&quot;2&quot;&gt;
        ///      &lt;set name=&quot;1&quot; cgdb_id=&quot;02&quot; value=&quot;7f08ef9f-dd47-415b-b002-827a0defcd2a&quot; /&gt;
        ///      &lt;set name=&quot;2&quot; cgdb_id=&quot;03&quot; value=&quot;755e0c90-42bc-4a0f-9b9e-993db8ea0bef&quot; /&gt;
        ///      &lt;set name=&quot;3&quot; cgdb_id=&quot;04&quot; value=&quot;979959f5-9470-40f9-9ca7-82463c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string setguids {
            get {
                return ResourceManager.GetString("setguids", resourceCulture);
            }
        }
    }
}
