//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtractorUtils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExtractorUtils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xml&gt;
        ///  &lt;cardsUrl value=&quot;https://api.fiveringsdb.com/cards/&quot; /&gt;
        ///  &lt;packsUrl value=&quot;https://api.fiveringsdb.com/packs/&quot; /&gt;
        ///  &lt;dbImageUrl value=&quot;http://www.thronesdb.com/bundles/cards/&quot; /&gt;
        ///  &lt;cgImageUrl value=&quot;http://lcg-cdn.fantasyflightgames.com/got2nd/&quot; /&gt;
        ///  &lt;properties&gt;
        ///    &lt;property octgn_name=&quot;Type&quot; type=&quot;property&quot; value=&quot;type_name&quot; /&gt;
        ///    &lt;property octgn_name=&quot;Faction&quot; type=&quot;property&quot; value=&quot;faction_name&quot; /&gt;
        ///    &lt;property octgn_name=&quot;Text&quot; type=&quot;property&quot; value=&quot;text&quot; isRich=&quot;True&quot;/&gt;
        ///    &lt;prop [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xml&gt;
        ///  &lt;sets&gt;
        ///    &lt;cycle value=&quot;0&quot;&gt;
        ///      &lt;set name=&quot;1&quot; cgdb_id=&quot;00&quot; value=&quot;b9353360-2f08-4517-a7d0-960b085d6ba4&quot; /&gt;
        ///    &lt;/cycle&gt;
        ///    &lt;cycle value=&quot;1&quot;&gt;
        ///      &lt;set name=&quot;1&quot; cgdb_id=&quot;01&quot; value=&quot;7a1d7bfd-db29-4812-8de1-01cf7ca73323&quot; /&gt;
        ///    &lt;/cycle&gt;
        ///    &lt;cycle value=&quot;2&quot;&gt;
        ///      &lt;set name=&quot;1&quot; cgdb_id=&quot;02&quot; value=&quot;84b585e5-12b1-4a6f-ab58-e995eb79795b&quot; /&gt;
        ///      &lt;set name=&quot;2&quot; cgdb_id=&quot;03&quot; value=&quot;ea59d7d7-5a8b-48e5-b246-229625967603&quot; /&gt;
        ///      &lt;set name=&quot;3&quot; cgdb_id=&quot;04&quot; value=&quot;840be9ee-a905-4316-8a25-1b8149 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string setguids {
            get {
                return ResourceManager.GetString("setguids", resourceCulture);
            }
        }
    }
}
